const Menu = [{
    id:1,
    image:"https://angelinos.com/cdn/shop/articles/How_Much_Milk_Coffee_in_a_Cappuccino.jpg?v=1701189122",
    name:"Cappuccino",
    category:"Coffee",
    price:"Rs.250",
    description:"A cappuccino is the perfect balance of espresso, steamed milk and foam. This coffee is all about the structure and the even splitting of all elements into equal thirds. An expertly made cappuccino should be rich, but not acidic and have a mildly sweet flavouring from the milk.",
},
{
    id:2,
    image: "https://brewespressocoffee.com/wp-content/uploads/2023/01/cappuccino.jpg",
    name:'Expresso',
    category: 'Coffee',
    price: 'Rs.200',
    description: 'Espresso is a concentrated, intense, and bold coffee that usually served in small cups.',
},
{
    id:3,
    image: "https://images.immediate.co.uk/production/volatile/sites/2/2024/10/lotus-coffee-f4ff392.gif?quality=90&resize=556,505",
    name:'Biscoff Cappuccino',
    category: 'Coffee',
    price: 'Rs.300',
    description: 'A Biscoff cappuccino is a coffee drink that combines the flavors of coffee and Lotus Biscoff cookies. ',   
},
{
    id:4,
    image: "https://www.savoryandsweetfood.com/wp-content/uploads/2016/10/IMG_1918.JPG.jpeg",
    name:'Club Sandwich',
    category: 'Sandwiches',
    price: 'Rs.120',
    description: 'A club sandwich or clubhouse sandwich, is a sandwich consisting of bread (traditionally toasted), sliced cooked poultry, fried bacon, lettuce, tomato, and mayonnaise.',   
},
{
    id:5,
    image: "https://www.honeywhatscooking.com/wp-content/uploads/2023/02/D011471F-A143-40E5-BF20-18ED2B5E4031-e1677048987625-720x881.jpg",
    name:'Veg Cheese Sandwich',
    category: 'Sandwiches',
    price: 'Rs.300',
    description: 'Indian Veg Grilled Cheese Sandwich that is made with cucumbers, tomatoes, onions, butter, cheese, green chutney, and chat masala on sandwich bread.',   
},
{
    id:6,
    image: "https://recipesblob.oetker.in/assets/3d6950a1502d453ca2e46e533c499f9d/636x382/tandoori-paneer-sandwich.webp",
    name:'Tandoori Paneer Sandwich',
    category: 'Sandwiches',
    price: 'Rs.400',
    description: 'Tandoori Paneer Sandwich has layers of spiced & smoked paneer, cilantro chutney and cheese all enclosed in a crusty bread! Perfect for brunch.',   
},
{
    id:7,
    image: "https://www.bravabod.com/wp-content/uploads/2022/10/Spaghetti-Aglio-e-Olio-with-Zucchini_E.jpg",
    name:'Agilo Olio',
    category: 'Pasta',
    price: 'Rs.400',
    description: 'Spaghetti aglio e olio with garlic, olive oil, red pepper flakes and parmesan.An easy Italian pasta recipe that uses only pantry basics.',   
},
{
    id:8,
    image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/4/8/2/FNM_050114-Classic-Red-Sauce-Recipe_s4x3.jpg.rend.hgtvcom.1280.960.suffix/1397491331300.webp",
    name:'Red Sauce Pasta',
    category: 'Pasta',
    price: 'Rs.400',
    description: 'Red Sauce Pasta is a delicious hot and tangy meal made by cooking pasta and tossing it in a tomato based sauce and seasoned with spices.',   
},
{
    id:9,
    image: "https://www.whiskaffair.com/wp-content/uploads/2021/05/White-Sauce-Paste-2-3.jpg",
    name:'White Sauce Pasta',
    category: 'Pasta',
    price: 'Rs.400',
    description: 'Creamy and cheesy White Sauce Pasta is the ultimate comfort food. Packed with veggies, this is also a great way to sneak in veggies for picky eaters.',   
},
];

export default Menu;